
name: Toy Workflow
run-name: Toy Worflow Exeuted!

on:
    - push

jobs:
       print_job-1:
            runs-on:   ubuntu-latest
            steps:
               - name: First Print Step
                 run: |
                   echo "Hello! I am printing page-1" 
               - name: Second Print Step
                 run: |
                   echo "Hello! I am printing page-2"
                  
